import {Injectable} from '@angular/core';
import {Song} from "./song";

@Injectable({
  providedIn: 'root'
})
export class SongSearchService {

  constructor() {
  }

  songTitles: Song[] = [
    new Song("Welcome To New York (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Blank Space (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Style (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Out Of The Woods (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("All You Had To Do Was Stay (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Shake It Off (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("I Wish You Would (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Bad Blood (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Wildest Dreams (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("How You Get The Girl (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("This Love (Taylor’s Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("I Know Places (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Clean (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Wonderland (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("You Are In Love (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("New Romantics (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("\"Slut!\" (Taylor's Version) (From The Vault)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Say Don't Go (Taylor's Version) (From The Vault)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Now That We Don't Talk (Taylor's Version) (From The Vault)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Suburban Legends (Taylor's Version) (From The Vault)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Is It Over Now? (Taylor's Version) (From The Vault)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Bad Blood (feat. Kendrick Lamar) (Taylor's Version)", "1989 (Taylor's Version) [Deluxe]", 2023),
    new Song("Welcome To New York (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Blank Space (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Style (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Out Of The Woods (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("All You Had To Do Was Stay (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Shake It Off (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("I Wish You Would (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Bad Blood (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Wildest Dreams (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("How You Get The Girl (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("This Love (Taylor’s Version)", "1989 (Taylor's Version)", 2023),
    new Song("I Know Places (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Clean (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("Wonderland (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("You Are In Love (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("New Romantics (Taylor's Version)", "1989 (Taylor's Version)", 2023),
    new Song("\"Slut!\" (Taylor's Version) (From The Vault)", "1989 (Taylor's Version)", 2023),
    new Song("Say Don't Go (Taylor's Version) (From The Vault)", "1989 (Taylor's Version)", 2023),
    new Song("Now That We Don't Talk (Taylor's Version) (From The Vault)", "1989 (Taylor's Version)", 2023),
    new Song("Suburban Legends (Taylor's Version) (From The Vault)", "1989 (Taylor's Version)", 2023),
    new Song("Is It Over Now? (Taylor's Version) (From The Vault)", "1989 (Taylor's Version)", 2023),
    new Song("Mine (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Sparks Fly (Taylor’s Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Back To December (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Speak Now (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Dear John (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Mean (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("The Story Of Us (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Never Grow Up (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Enchanted (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Better Than Revenge (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Innocent (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Haunted (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Last Kiss (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Long Live (Taylor's Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Ours (Taylor’s Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Superman (Taylor’s Version)", "Speak Now (Taylor's Version)", 2023),
    new Song("Electric Touch (feat. Fall Out Boy) (Taylor’s Version) (From The Vault)", "Speak Now (Taylor's Version)", 2023),
    new Song("When Emma Falls in Love (Taylor’s Version) (From The Vault)", "Speak Now (Taylor's Version)", 2023),
    new Song("I Can See You (Taylor’s Version) (From The Vault)", "Speak Now (Taylor's Version)", 2023),
    new Song("Castles Crumbling (feat. Hayley Williams) (Taylor’s Version) (From The Vault)", "Speak Now (Taylor's Version)", 2023),
    new Song("Foolish One (Taylor’s Version) (From The Vault)", "Speak Now (Taylor's Version)", 2023),
    new Song("Timeless (Taylor’s Version) (From The Vault)", "Speak Now (Taylor's Version)", 2023),
    new Song("Lavender Haze", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Maroon", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Anti-Hero", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Snow On The Beach (feat. Lana Del Rey)", "Midnights (The Til Dawn Edition)", 2023),
    new Song("You're On Your Own, Kid", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Midnight Rain", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Question...?", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Vigilante Shit", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Bejeweled", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Labyrinth", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Karma", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Sweet Nothing", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Mastermind", "Midnights (The Til Dawn Edition)", 2023),
    new Song("The Great War", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Bigger Than The Whole Sky", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Paris", "Midnights (The Til Dawn Edition)", 2023),
    new Song("High Infidelity", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Glitch", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Would've, Could've, Should've", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Dear Reader", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Hits Different", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Snow On The Beach (feat. More Lana Del Rey)", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Karma (feat. Ice Spice)", "Midnights (The Til Dawn Edition)", 2023),
    new Song("Lavender Haze", "Midnights (3am Edition)", 2022),
    new Song("Maroon", "Midnights (3am Edition)", 2022),
    new Song("Anti-Hero", "Midnights (3am Edition)", 2022),
    new Song("Snow On The Beach (feat. Lana Del Rey)", "Midnights (3am Edition)", 2022),
    new Song("You're On Your Own, Kid", "Midnights (3am Edition)", 2022),
    new Song("Midnight Rain", "Midnights (3am Edition)", 2022),
    new Song("Question...?", "Midnights (3am Edition)", 2022),
    new Song("Vigilante Shit", "Midnights (3am Edition)", 2022),
    new Song("Bejeweled", "Midnights (3am Edition)", 2022),
    new Song("Labyrinth", "Midnights (3am Edition)", 2022),
    new Song("Karma", "Midnights (3am Edition)", 2022),
    new Song("Sweet Nothing", "Midnights (3am Edition)", 2022),
    new Song("Mastermind", "Midnights (3am Edition)", 2022),
    new Song("The Great War", "Midnights (3am Edition)", 2022),
    new Song("Bigger Than The Whole Sky", "Midnights (3am Edition)", 2022),
    new Song("Paris", "Midnights (3am Edition)", 2022),
    new Song("High Infidelity", "Midnights (3am Edition)", 2022),
    new Song("Glitch", "Midnights (3am Edition)", 2022),
    new Song("Would've, Could've, Should've", "Midnights (3am Edition)", 2022),
    new Song("Dear Reader", "Midnights (3am Edition)", 2022),
    new Song("Lavender Haze", "Midnights", 2022),
    new Song("Maroon", "Midnights", 2022),
    new Song("Anti-Hero", "Midnights", 2022),
    new Song("Snow On The Beach (feat. Lana Del Rey)", "Midnights", 2022),
    new Song("You're On Your Own, Kid", "Midnights", 2022),
    new Song("Midnight Rain", "Midnights", 2022),
    new Song("Question...?", "Midnights", 2022),
    new Song("Vigilante Shit", "Midnights", 2022),
    new Song("Bejeweled", "Midnights", 2022),
    new Song("Labyrinth", "Midnights", 2022),
    new Song("Karma", "Midnights", 2022),
    new Song("Sweet Nothing", "Midnights", 2022),
    new Song("Mastermind", "Midnights", 2022),
    new Song("State Of Grace (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Red (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Treacherous (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("I Knew You Were Trouble (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("All Too Well (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("22 (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("I Almost Do (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("We Are Never Ever Getting Back Together (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Stay Stay Stay (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("The Last Time (feat. Gary Lightbody of Snow Patrol) (Taylor’s Version)", "Red (Taylor's Version)", 2021),
    new Song("Holy Ground (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Sad Beautiful Tragic (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("The Lucky One (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Everything Has Changed (feat. Ed Sheeran) (Taylor’s Version)", "Red (Taylor's Version)", 2021),
    new Song("Starlight (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Begin Again (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("The Moment I Knew (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Come Back...Be Here (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Girl At Home (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("State Of Grace (Acoustic Version) (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Ronan (Taylor's Version)", "Red (Taylor's Version)", 2021),
    new Song("Better Man (Taylor's Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("Nothing New (feat. Phoebe Bridgers) (Taylor’s Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("Babe (Taylor's Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("Message In A Bottle (Taylor's Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("I Bet You Think About Me (feat. Chris Stapleton) (Taylor’s Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("Forever Winter (Taylor's Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("Run (feat. Ed Sheeran) (Taylor’s Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("The Very First Night (Taylor's Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)", "Red (Taylor's Version)", 2021),
    new Song("Fearless (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Fifteen (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Love Story (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Hey Stephen (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("White Horse (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("You Belong With Me (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Breathe (feat. Colbie Caillat) (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Tell Me Why (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("You’re Not Sorry (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("The Way I Loved You (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Forever & Always (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("The Best Day (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Change (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Jump Then Fall (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Untouchable (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Forever & Always (Piano Version) (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Come In With The Rain (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Superstar (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("The Other Side Of The Door (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("Today Was A Fairytale (Taylor’s Version)", "Fearless (Taylor's Version)", 2021),
    new Song("You All Over Me (feat. Maren Morris) (Taylor’s Version) (From The Vault)", "Fearless (Taylor's Version)", 2021),
    new Song("Mr. Perfectly Fine (Taylor’s Version) (From The Vault)", "Fearless (Taylor's Version)", 2021),
    new Song("We Were Happy (Taylor’s Version) (From The Vault)", "Fearless (Taylor's Version)", 2021),
    new Song("That’s When (feat. Keith Urban) (Taylor’s Version) (From The Vault)", "Fearless (Taylor's Version)", 2021),
    new Song("Don’t You (Taylor’s Version) (From The Vault)", "Fearless (Taylor's Version)", 2021),
    new Song("Bye Bye Baby (Taylor’s Version) (From The Vault)", "Fearless (Taylor's Version)", 2021),
    new Song("willow", "evermore (deluxe version)", 2021),
    new Song("champagne problems", "evermore (deluxe version)", 2021),
    new Song("gold rush", "evermore (deluxe version)", 2021),
    new Song("‘tis the damn season", "evermore (deluxe version)", 2021),
    new Song("tolerate it", "evermore (deluxe version)", 2021),
    new Song("no body, no crime (feat. HAIM)", "evermore (deluxe version)", 2021),
    new Song("happiness", "evermore (deluxe version)", 2021),
    new Song("dorothea", "evermore (deluxe version)", 2021),
    new Song("coney island (feat. The National)", "evermore (deluxe version)", 2021),
    new Song("ivy", "evermore (deluxe version)", 2021),
    new Song("cowboy like me", "evermore (deluxe version)", 2021),
    new Song("long story short", "evermore (deluxe version)", 2021),
    new Song("marjorie", "evermore (deluxe version)", 2021),
    new Song("closure", "evermore (deluxe version)", 2021),
    new Song("evermore (feat. Bon Iver)", "evermore (deluxe version)", 2021),
    new Song("right where you left me - bonus track", "evermore (deluxe version)", 2021),
    new Song("it’s time to go - bonus track", "evermore (deluxe version)", 2021),
    new Song("willow", "evermore", 2020),
    new Song("champagne problems", "evermore", 2020),
    new Song("gold rush", "evermore", 2020),
    new Song("‘tis the damn season", "evermore", 2020),
    new Song("tolerate it", "evermore", 2020),
    new Song("no body, no crime (feat. HAIM)", "evermore", 2020),
    new Song("happiness", "evermore", 2020),
    new Song("dorothea", "evermore", 2020),
    new Song("coney island (feat. The National)", "evermore", 2020),
    new Song("ivy", "evermore", 2020),
    new Song("cowboy like me", "evermore", 2020),
    new Song("long story short", "evermore", 2020),
    new Song("marjorie", "evermore", 2020),
    new Song("closure", "evermore", 2020),
    new Song("evermore (feat. Bon Iver)", "evermore", 2020),
    new Song("the 1", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("cardigan", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("the last great american dynasty", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("exile (feat. Bon Iver)", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("my tears ricochet", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("mirrorball", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("seven", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("august", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("this is me trying", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("illicit affairs", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("invisible string", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("mad woman", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("epiphany", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("betty", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("peace", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("hoax", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("the lakes - bonus track", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("the 1 - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("cardigan - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("the last great american dynasty - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("exile (feat. Bon Iver) - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("my tears ricochet - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("mirrorball - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("seven - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("august - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("this is me trying - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("illicit affairs - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("invisible string - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("mad woman - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("epiphany - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("betty - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("peace - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("hoax - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("the lakes - the long pond studio sessions", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition]", 2020),
    new Song("the 1", "folklore (deluxe version)", 2020),
    new Song("cardigan", "folklore (deluxe version)", 2020),
    new Song("the last great american dynasty", "folklore (deluxe version)", 2020),
    new Song("exile (feat. Bon Iver)", "folklore (deluxe version)", 2020),
    new Song("my tears ricochet", "folklore (deluxe version)", 2020),
    new Song("mirrorball", "folklore (deluxe version)", 2020),
    new Song("seven", "folklore (deluxe version)", 2020),
    new Song("august", "folklore (deluxe version)", 2020),
    new Song("this is me trying", "folklore (deluxe version)", 2020),
    new Song("illicit affairs", "folklore (deluxe version)", 2020),
    new Song("invisible string", "folklore (deluxe version)", 2020),
    new Song("mad woman", "folklore (deluxe version)", 2020),
    new Song("epiphany", "folklore (deluxe version)", 2020),
    new Song("betty", "folklore (deluxe version)", 2020),
    new Song("peace", "folklore (deluxe version)", 2020),
    new Song("hoax", "folklore (deluxe version)", 2020),
    new Song("the lakes - bonus track", "folklore (deluxe version)", 2020),
    new Song("the 1", "folklore", 2020),
    new Song("cardigan", "folklore", 2020),
    new Song("the last great american dynasty", "folklore", 2020),
    new Song("exile (feat. Bon Iver)", "folklore", 2020),
    new Song("my tears ricochet", "folklore", 2020),
    new Song("mirrorball", "folklore", 2020),
    new Song("seven", "folklore", 2020),
    new Song("august", "folklore", 2020),
    new Song("this is me trying", "folklore", 2020),
    new Song("illicit affairs", "folklore", 2020),
    new Song("invisible string", "folklore", 2020),
    new Song("mad woman", "folklore", 2020),
    new Song("epiphany", "folklore", 2020),
    new Song("betty", "folklore", 2020),
    new Song("peace", "folklore", 2020),
    new Song("hoax", "folklore", 2020),
    new Song("I Forgot That You Existed", "Lover", 2019),
    new Song("Cruel Summer", "Lover", 2019),
    new Song("Lover", "Lover", 2019),
    new Song("The Man", "Lover", 2019),
    new Song("The Archer", "Lover", 2019),
    new Song("I Think He Knows", "Lover", 2019),
    new Song("Miss Americana & The Heartbreak Prince", "Lover", 2019),
    new Song("Paper Rings", "Lover", 2019),
    new Song("Cornelia Street", "Lover", 2019),
    new Song("Death By A Thousand Cuts", "Lover", 2019),
    new Song("London Boy", "Lover", 2019),
    new Song("Soon You’ll Get Better (feat. The Chicks)", "Lover", 2019),
    new Song("False God", "Lover", 2019),
    new Song("You Need To Calm Down", "Lover", 2019),
    new Song("Afterglow", "Lover", 2019),
    new Song("ME! (feat. Brendon Urie of Panic! At The Disco)", "Lover", 2019),
    new Song("It’s Nice To Have A Friend", "Lover", 2019),
    new Song("Daylight", "Lover", 2019),
    new Song("...Ready For It?", "reputation", 2017),
    new Song("End Game", "reputation", 2017),
    new Song("I Did Something Bad", "reputation", 2017),
    new Song("Don’t Blame Me", "reputation", 2017),
    new Song("Delicate", "reputation", 2017),
    new Song("Look What You Made Me Do", "reputation", 2017),
    new Song("So It Goes...", "reputation", 2017),
    new Song("Gorgeous", "reputation", 2017),
    new Song("Getaway Car", "reputation", 2017),
    new Song("King Of My Heart", "reputation", 2017),
    new Song("Dancing With Our Hands Tied", "reputation", 2017),
    new Song("Dress", "reputation", 2017),
    new Song("This Is Why We Can't Have Nice Things", "reputation", 2017),
    new Song("Call It What You Want", "reputation", 2017),
    new Song("New Year’s Day", "reputation", 2017),
    new Song("All Too Well", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Wildest Dreams", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("The Best Day", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Red", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Holy Ground", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Teardrops On My Guitar - Radio Single Remix", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Our Song", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("22", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("I Knew You Were Trouble.", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("I Don’t Wanna Live Forever (Fifty Shades Darker)", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Mean", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("How You Get The Girl", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("So It Goes...", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Fifteen", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Mine", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Sparks Fly", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("State Of Grace", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Haunted", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Never Grow Up", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Treacherous", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Babe", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Welcome To New York", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Fearless", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Enchanted", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Change", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Ours", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Out Of The Woods", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Come Back...Be Here", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("A Place in this World", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("This Love", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("The Lucky One", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Invisible", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Breathe", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Better Man", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Jump Then Fall", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Begin Again", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Tied Together with a Smile", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("The Story Of Us", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Forever & Always", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Hey Stephen", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Speak Now", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Wonderland", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("White Horse", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("I'm Only Me When I'm With You", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Starlight", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("I Know Places", "reputation Stadium Tour Surprise Song Playlist", 2017),
    new Song("Welcome To New York", "1989 (Deluxe Edition)", 2014),
    new Song("Blank Space", "1989 (Deluxe Edition)", 2014),
    new Song("Style", "1989 (Deluxe Edition)", 2014),
    new Song("Out Of The Woods", "1989 (Deluxe Edition)", 2014),
    new Song("All You Had To Do Was Stay", "1989 (Deluxe Edition)", 2014),
    new Song("Shake It Off", "1989 (Deluxe Edition)", 2014),
    new Song("I Wish You Would", "1989 (Deluxe Edition)", 2014),
    new Song("Bad Blood", "1989 (Deluxe Edition)", 2014),
    new Song("Wildest Dreams", "1989 (Deluxe Edition)", 2014),
    new Song("How You Get The Girl", "1989 (Deluxe Edition)", 2014),
    new Song("This Love", "1989 (Deluxe Edition)", 2014),
    new Song("I Know Places", "1989 (Deluxe Edition)", 2014),
    new Song("Clean", "1989 (Deluxe Edition)", 2014),
    new Song("Wonderland", "1989 (Deluxe Edition)", 2014),
    new Song("You Are In Love", "1989 (Deluxe Edition)", 2014),
    new Song("New Romantics", "1989 (Deluxe Edition)", 2014),
    new Song("I Know Places - Voice Memo", "1989 (Deluxe Edition)", 2014),
    new Song("I Wish You Would - Voice Memo", "1989 (Deluxe Edition)", 2014),
    new Song("Blank Space - Voice Memo", "1989 (Deluxe Edition)", 2014),
    new Song("Welcome To New York", "1989", 2014),
    new Song("Blank Space", "1989", 2014),
    new Song("Style", "1989", 2014),
    new Song("Out Of The Woods", "1989", 2014),
    new Song("All You Had To Do Was Stay", "1989", 2014),
    new Song("Shake It Off", "1989", 2014),
    new Song("I Wish You Would", "1989", 2014),
    new Song("Bad Blood", "1989", 2014),
    new Song("Wildest Dreams", "1989", 2014),
    new Song("How You Get The Girl", "1989", 2014),
    new Song("This Love", "1989", 2014),
    new Song("I Know Places", "1989", 2014),
    new Song("Clean", "1989", 2014),
    new Song("State Of Grace", "Red (Deluxe Edition)", 2012),
    new Song("Red", "Red (Deluxe Edition)", 2012),
    new Song("Treacherous", "Red (Deluxe Edition)", 2012),
    new Song("I Knew You Were Trouble.", "Red (Deluxe Edition)", 2012),
    new Song("All Too Well", "Red (Deluxe Edition)", 2012),
    new Song("22", "Red (Deluxe Edition)", 2012),
    new Song("I Almost Do", "Red (Deluxe Edition)", 2012),
    new Song("We Are Never Ever Getting Back Together", "Red (Deluxe Edition)", 2012),
    new Song("Stay Stay Stay", "Red (Deluxe Edition)", 2012),
    new Song("The Last Time", "Red (Deluxe Edition)", 2012),
    new Song("Holy Ground", "Red (Deluxe Edition)", 2012),
    new Song("Sad Beautiful Tragic", "Red (Deluxe Edition)", 2012),
    new Song("The Lucky One", "Red (Deluxe Edition)", 2012),
    new Song("Everything Has Changed", "Red (Deluxe Edition)", 2012),
    new Song("Starlight", "Red (Deluxe Edition)", 2012),
    new Song("Begin Again", "Red (Deluxe Edition)", 2012),
    new Song("The Moment I Knew", "Red (Deluxe Edition)", 2012),
    new Song("Come Back...Be Here", "Red (Deluxe Edition)", 2012),
    new Song("Girl At Home", "Red (Deluxe Edition)", 2012),
    new Song("Treacherous - Original Demo Recording", "Red (Deluxe Edition)", 2012),
    new Song("Red - Original Demo Recording", "Red (Deluxe Edition)", 2012),
    new Song("State Of Grace - Acoustic", "Red (Deluxe Edition)", 2012),
    new Song("State Of Grace", "Red", 2012),
    new Song("Red", "Red", 2012),
    new Song("Treacherous", "Red", 2012),
    new Song("I Knew You Were Trouble.", "Red", 2012),
    new Song("All Too Well", "Red", 2012),
    new Song("22", "Red", 2012),
    new Song("I Almost Do", "Red", 2012),
    new Song("We Are Never Ever Getting Back Together", "Red", 2012),
    new Song("Stay Stay Stay", "Red", 2012),
    new Song("The Last Time", "Red", 2012),
    new Song("Holy Ground", "Red", 2012),
    new Song("Sad Beautiful Tragic", "Red", 2012),
    new Song("The Lucky One", "Red", 2012),
    new Song("Everything Has Changed", "Red", 2012),
    new Song("Starlight", "Red", 2012),
    new Song("Begin Again", "Red", 2012),
    new Song("Sparks Fly - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Mine - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("The Story Of Us - Live", "Speak Now World Tour Live", 2010),
    new Song("Mean - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Ours - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Back To December/Apologize/You're Not Sorry - Live/2011/Medley", "Speak Now World Tour Live", 2010),
    new Song("Better Than Revenge - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Speak Now - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Last Kiss - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Drops Of Jupiter - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Bette Davis Eyes - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("I Want You Back - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Dear John - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Enchanted - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Haunted - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Long Live - Live/2011", "Speak Now World Tour Live", 2010),
    new Song("Mine", "Speak Now (Deluxe Edition)", 2010),
    new Song("Sparks Fly", "Speak Now (Deluxe Edition)", 2010),
    new Song("Back To December", "Speak Now (Deluxe Edition)", 2010),
    new Song("Speak Now", "Speak Now (Deluxe Edition)", 2010),
    new Song("Dear John", "Speak Now (Deluxe Edition)", 2010),
    new Song("Mean", "Speak Now (Deluxe Edition)", 2010),
    new Song("The Story Of Us", "Speak Now (Deluxe Edition)", 2010),
    new Song("Never Grow Up", "Speak Now (Deluxe Edition)", 2010),
    new Song("Enchanted", "Speak Now (Deluxe Edition)", 2010),
    new Song("Better Than Revenge", "Speak Now (Deluxe Edition)", 2010),
    new Song("Innocent", "Speak Now (Deluxe Edition)", 2010),
    new Song("Haunted", "Speak Now (Deluxe Edition)", 2010),
    new Song("Last Kiss", "Speak Now (Deluxe Edition)", 2010),
    new Song("Long Live", "Speak Now (Deluxe Edition)", 2010),
    new Song("Ours", "Speak Now (Deluxe Edition)", 2010),
    new Song("If This Was A Movie", "Speak Now (Deluxe Edition)", 2010),
    new Song("Superman", "Speak Now (Deluxe Edition)", 2010),
    new Song("Back To December - Acoustic", "Speak Now (Deluxe Edition)", 2010),
    new Song("Haunted - Acoustic Version", "Speak Now (Deluxe Edition)", 2010),
    new Song("Mine - POP Mix", "Speak Now (Deluxe Edition)", 2010),
    new Song("Mine", "Speak Now", 2010),
    new Song("Sparks Fly", "Speak Now", 2010),
    new Song("Back To December", "Speak Now", 2010),
    new Song("Speak Now", "Speak Now", 2010),
    new Song("Dear John", "Speak Now", 2010),
    new Song("Mean", "Speak Now", 2010),
    new Song("The Story Of Us", "Speak Now", 2010),
    new Song("Never Grow Up", "Speak Now", 2010),
    new Song("Enchanted", "Speak Now", 2010),
    new Song("Better Than Revenge", "Speak Now", 2010),
    new Song("Innocent", "Speak Now", 2010),
    new Song("Haunted", "Speak Now", 2010),
    new Song("Last Kiss", "Speak Now", 2010),
    new Song("Long Live", "Speak Now", 2010),
    new Song("Jump Then Fall", "Fearless Platinum Edition", 2008),
    new Song("Untouchable", "Fearless Platinum Edition", 2008),
    new Song("Forever & Always - Piano Version", "Fearless Platinum Edition", 2008),
    new Song("Come In With The Rain", "Fearless Platinum Edition", 2008),
    new Song("SuperStar", "Fearless Platinum Edition", 2008),
    new Song("The Other Side Of The Door", "Fearless Platinum Edition", 2008),
    new Song("Fearless", "Fearless Platinum Edition", 2008),
    new Song("Fifteen", "Fearless Platinum Edition", 2008),
    new Song("Love Story", "Fearless Platinum Edition", 2008),
    new Song("Hey Stephen", "Fearless Platinum Edition", 2008),
    new Song("White Horse", "Fearless Platinum Edition", 2008),
    new Song("You Belong With Me", "Fearless Platinum Edition", 2008),
    new Song("Breathe", "Fearless Platinum Edition", 2008),
    new Song("Tell Me Why", "Fearless Platinum Edition", 2008),
    new Song("You're Not Sorry", "Fearless Platinum Edition", 2008),
    new Song("The Way I Loved You", "Fearless Platinum Edition", 2008),
    new Song("Forever & Always", "Fearless Platinum Edition", 2008),
    new Song("The Best Day", "Fearless Platinum Edition", 2008),
    new Song("Change", "Fearless Platinum Edition", 2008),
    new Song("Fearless", "Fearless", 2008),
    new Song("Fifteen", "Fearless", 2008),
    new Song("Love Story", "Fearless", 2008),
    new Song("Hey Stephen", "Fearless", 2008),
    new Song("White Horse", "Fearless", 2008),
    new Song("You Belong With Me", "Fearless", 2008),
    new Song("Breathe", "Fearless", 2008),
    new Song("Tell Me Why", "Fearless", 2008),
    new Song("You're Not Sorry", "Fearless", 2008),
    new Song("The Way I Loved You", "Fearless", 2008),
    new Song("Forever & Always", "Fearless", 2008),
    new Song("The Best Day", "Fearless", 2008),
    new Song("Change", "Fearless", 2008),
    new Song("Love Story - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Fearless - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Beautiful Eyes - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Untouchable - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Teardrops On My Guitar - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Picture To Burn - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Should've Said No - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Change - Live From Clear Channel Stripped 2008", "Live From Clear Channel Stripped 2008", 2008),
    new Song("Tim McGraw", "Taylor Swift", 2006),
    new Song("Picture To Burn", "Taylor Swift", 2006),
    new Song("Teardrops On My Guitar - Radio Single Remix", "Taylor Swift", 2006),
    new Song("A Place in this World", "Taylor Swift", 2006),
    new Song("Cold As You", "Taylor Swift", 2006),
    new Song("The Outside", "Taylor Swift", 2006),
    new Song("Tied Together with a Smile", "Taylor Swift", 2006),
    new Song("Stay Beautiful", "Taylor Swift", 2006),
    new Song("Should've Said No", "Taylor Swift", 2006),
    new Song("Mary's Song (Oh My My My)", "Taylor Swift", 2006),
    new Song("Our Song", "Taylor Swift", 2006),
    new Song("I'm Only Me When I'm With You", "Taylor Swift", 2006),
    new Song("Invisible", "Taylor Swift", 2006),
    new Song("A Perfectly Good Heart", "Taylor Swift", 2006),
    new Song("Teardrops on My Guitar - Pop Version", "Taylor Swift", 2006),
  ];

  find(input: string): Song[] {
    return this.songTitles.filter(song => song.title.toLowerCase().includes(input.toLowerCase()));
  }

}
