# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TayQuiz

    strategy:
      matrix:
        node-version: [20.11.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: TayQuiz/package-lock.json
    - run: npm install
    - run: npm install -g @ionic/cli
    - run: npm version $(date +%Y.%m%d.%H%M)
    - run: ionic build --prod
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        # Build directory to deploy
        build_dir: TayQuiz/www
        # Whether to treat build_dir as an absolute path
        # absolute_build_dir: # optional, default is false
        # Allow Jekyll to build your site
        jekyll: false
        verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
